apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
spec:
  dspVersion: v2
  objectStorage:
    minio:
      deploy: true
      image: 'minio/minio:RELEASE.2020-12-18T03-27-42Z'
  mlpipelineUI:
    image: docker-na-public.artifactory.swg-devops.com/sys-knative-upstream-ci-team-z-docker-local/kubeflow-images/frontend:latest
